server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka
      password: eureka-secret

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:eureka-secret@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
